### ISSUE TITLE
transformation matrix

### ISSUE THREAD

**Issue by GiovanniSena** [GiovanniSena/LSFM#2]
We have finally concluded that only a pure "rigid translation" makes sense for our system since these are the only transformations we can physically implement. The idea is that we will find the best "effective" translation that best register the two images, even though this might be different from the actual translation occurred in space.
Thus, can we simplify the form of the transformation matrix to reflect this, and can we avoid caluclating rotation angles? I am hoping we could save some computatinal time in doing so.

**Comment by PaoloGB** [comment]
Using a rigid translation is already possible in the code. Simply define 
transftype=translation
in the cfg file and the code will do it.

In fact, the version of the cfg file I see already has that option set.
