### ISSUE TITLE
Webcam?

### ISSUE THREAD

**Issue by GiovanniSena** [GiovanniSena/LSFM#5]
The original idea for the webcam was to see the leaves during long experiments. If we cannot position it in a way to avoid reflections from the LEDs, this is useless. 
Maybe we could use an IR camera (Noir) for Raspberry pi?
To simplify, this could be taken out of the MATLAB code, and a second independent window opened, if required.

**Comment by PaoloGB** [comment]
An easy and non destructive way to do this is to comment out the line

TAB3_GUI(tab_3);

in "main_GUI.m"

Once that is done, the webcam tab will not be shown but it can easily be reinstated if needed.
Changing more than this would require testing on your side to ensure nothing is broken in the code.

**Comment by GiovanniSena** [comment]
Sounds good to me.
Can you do that and add comments in the code about it?

Many thanks,
Giovanni

----------------------------------------------------
Giovanni Sena, PhD
Lecturer | Imperial College London
www3.imperial.ac.uk/people/g.sena<http://www3.imperial.ac.uk/people/g.sena>
----------------------------------------------------

On 17 May 2017, 22:53 +0100, Paolo Baesso <notifications@github.com>, wrote:

An easy and non destructive way to do this is to comment out the line

TAB3_GUI(tab_3);

in "main_GUI.m"

Once that is done, the webcam tab will not be shown but it can easily be reinstated if needed.
Changing more than this would require testing on your side to ensure nothing is broken in the code.

**Comment by PaoloGB** [comment]
Done.
I will close the issue.
